dataset_dirs: ["/path/to/imageset"]
gpu_ids: [0]
pretrained_model: null
signal_set: "SHORT"
signal_set_origin: "SHORT"
class_set: "BASIC5ZYG"
image_dim: 256
num_keypoints: 1
model_architecture: "HG"
batch_size: 16
num_epochs: 32
learning_rate: 0.0001
learning_rate_decay_interval: 5
learning_rate_decay_factor: 1
report_interval: 50
plot_confidence_maps: False
validation_ratio: 0.1
sigma: 10
stride: 4
heatmap_peak_threshold: 0.4
